name: Update repo

on:
  schedule:
    - cron: '0 14 * * *' 
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Commit and Push changes
      run: |
        git config --global user.name "Lucas Mori"
        git config --global user.email "lucaskmori@gmail.com"
        git add .
        git commit -m "Update files" || echo "No changes to commit"
        git push